title: Andrei Epure
author: andreiepure
description: > # this means to ignore newlines until "baseurl:"
  Andrei Epure, Software Engineer.

header_pages:
  - about.md

# social links
twitter_username: andrei_cs_pub
github_username:  andreiepure
github_username:  andrei-epure-sonarsource

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
