title: Andrei Epure
author: andreiepure
tagline: Web log.
description: Andrei Epure's web log.
url: andreiepure.ro

# social links
twitter_username: andrei_cs_pub

# the below is for blog posts
show_excerpts: true # set to false to remove excerpts on the homepage

header_pages:
 - about.md

theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag