title: Andrei Epure
author: Andrei Epure
tagline: Andrei Epure, Software Engineer.
description: Personal website of Andrei Epure, a passionate Software Engineer who is building tools to make developers write better, safer code.
url: andreiepure.ro

header_pages:
  - about.md

# social links
twitter_username: andrei_cs_pub
github_username:  andreiepure

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag