title: Andrei Epure
author: andreiepure
tagline: Andrei Epure, Software Engineer.
description: Personal website of Andrei Epure, a passionate Software Engineer who is building tools to make developers write better, safer code.
url: andreiepure.ro

# social links
twitter_username: andrei_cs_pub

# the below is for blog posts
show_excerpts: true # set to false to remove excerpts on the homepage

header_pages:
 - about.md

theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag