title: Andrei Epure
description: Andrei Epure's web log.
url: andreiepure.ro

# social links
twitter_username: andrei_cs_pub

# the below is for blog posts
show_excerpts: false # set to false to remove excerpts on the homepage

theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag